theme: jekyll-theme-slate
title: "Ann Lewis, CTO MoveOn.org"
description: "Ann Lewis is is a technical leader, architect, and active coder with domain expertise in political tech, distributed systems, ecommerce, edtech, and startups, using a variety of technologies, languages, and platforms. She's passionate about cultivating great engineering teams, and building tech that enables collective action and mobilizes Americans at scale. "
logo: https://s3.amazonaws.com/annlewis.tech/ann_hs.jpg
image: https://s3.amazonaws.com/annlewis.tech/ann_hs.jpg
linkedin: theannlewis
github: mathemagica
medium: ann_lewis
twitter: ann_lewis 
facebook: theannlewis 
